export const menuItems = [
  { label: 'Tổng quan', icon: 'bi-house-door' },
  { label: 'Thông tin trẻ', icon: 'bi-person-badge' },
  { label: 'Ngân hàng mục tiêu', icon: 'bi-bullseye', active: true },
  { label: 'Kế hoạch can thiệp', icon: 'bi-calendar2-check' },
  { label: 'Báo cáo can thiệp', icon: 'bi-clipboard2-data' },
  { label: 'Chờ duyệt', icon: 'bi-clock' },
  { label: 'Giỏ mục tiêu', icon: 'bi-cart3' },
];

export const fields = [
  {
    id: 1,
    name: 'Ngôn ngữ hiểu',
    key: 'nnh',
    desc: 'Hiểu và thực hiện các yêu cầu, chỉ dẫn trong giao tiếp.',
    count: 36,
    color: 'blue',
    child: '👧',
    symbol: '💡',
  },
  {
    id: 2,
    name: 'Ngôn ngữ diễn đạt',
    key: 'nndd',
    desc: 'Diễn đạt nhu cầu, ý tưởng bằng lời nói, cử chỉ, hình ảnh.',
    count: 42,
    color: 'yellow',
    child: '👦👧',
    symbol: '💬',
  },
  {
    id: 3,
    name: 'Nhận thức',
    key: 'nt',
    desc: 'Nhận biết, phân loại, so sánh, ghi nhớ và giải quyết vấn đề.',
    count: 38,
    color: 'orange',
    child: '👦',
    symbol: '🔎',
  },
  {
    id: 4,
    name: 'Vận động tinh',
    key: 'vdt',
    desc: 'Sử dụng các cơ nhỏ của bàn tay, ngón tay một cách khéo léo.',
    count: 33,
    color: 'green',
    child: '👦',
    symbol: '🧮',
  },
  {
    id: 5,
    name: 'Vận động thô',
    key: 'vdtho',
    desc: 'Sử dụng các cơ lớn của cơ thể để di chuyển và giữ thăng bằng.',
    count: 29,
    color: 'blue',
    child: '🏃',
    symbol: '🔺',
  },
  {
    id: 6,
    name: 'Cá nhân xã hội',
    key: 'cnxh',
    desc: 'Kỹ năng tự chăm sóc, tương tác xã hội và ứng xử phù hợp.',
    count: 41,
    color: 'yellow',
    child: '🧒👧',
    symbol: '🧸',
  },
  {
    id: 7,
    name: 'Hành vi',
    key: 'hv',
    desc: 'Điều chỉnh hành vi, cảm xúc và tuân thủ các quy tắc.',
    count: 26,
    color: 'pink',
    child: '😟',
    symbol: '🌀',
  },
  {
    id: 8,
    name: 'Tập trung chú ý',
    key: 'ttcy',
    desc: 'Duy trì sự chú ý vào nhiệm vụ trong một khoảng thời gian.',
    count: 35,
    color: 'orange',
    child: '✍️',
    symbol: '⏳',
  },
];
