export const menuItems = [
  { label: 'Tổng quan', icon: 'bi-house-door' },
  { label: 'Thông tin trẻ', icon: 'bi-person-bounding-box', active: true },
  { label: 'Chương trình can thiệp', icon: 'bi-journal-check' },
  { label: 'Kế hoạch can thiệp', icon: 'bi-calendar2-check' },
  { label: 'Nhật ký can thiệp', icon: 'bi-clipboard2-pulse' },
  { label: 'Báo cáo', icon: 'bi-clock' },
  { label: 'Lịch hẹn', icon: 'bi-calendar-event' },
  { label: 'Tin nhắn', icon: 'bi-envelope' },
  { label: 'Cài đặt', icon: 'bi-gear' },
];

export const children = [
  {
    id: 1,
    name: 'Nguyễn Minh Khang',
    birthday: '28/05/2019',
    gender: 'Nam',
    group: 'Nhóm 1',
    status: 'Đang can thiệp',
    statusType: 'active',
    teacher: 'Cô Nguyễn Thị An',
    teacherNote: 'Giáo viên phụ trách',
    avatar: 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=420&q=80',
    teacherAvatar: 'https://i.pravatar.cc/80?img=47',
  },
  {
    id: 2,
    name: 'Trần Bảo Châu',
    birthday: '14/09/2018',
    gender: 'Nữ',
    group: 'Nhóm 1',
    status: 'Đang can thiệp',
    statusType: 'active',
    teacher: 'Cô Lê Thị Minh',
    teacherNote: 'Giáo viên phụ trách',
    avatar: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=420&q=80',
    teacherAvatar: 'https://i.pravatar.cc/80?img=32',
  },
  {
    id: 3,
    name: 'Phạm Gia Hưng',
    birthday: '03/12/2019',
    gender: 'Nam',
    group: 'Nhóm 2',
    status: 'Tạm dừng',
    statusType: 'paused',
    teacher: 'Cô Nguyễn Thị An',
    teacherNote: 'Giáo viên phụ trách',
    avatar: 'https://images.unsplash.com/photo-1542810634-71277d95dcbb?auto=format&fit=crop&w=420&q=80',
    teacherAvatar: 'https://i.pravatar.cc/80?img=47',
  },
  {
    id: 4,
    name: 'Lê Hà My',
    birthday: '21/07/2018',
    gender: 'Nữ',
    group: 'Nhóm 2',
    status: 'Đang can thiệp',
    statusType: 'active',
    teacher: 'Cô Lê Thị Minh',
    teacherNote: 'Giáo viên phụ trách',
    avatar: 'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?auto=format&fit=crop&w=420&q=80',
    teacherAvatar: 'https://i.pravatar.cc/80?img=32',
  },
  {
    id: 5,
    name: 'Hoàng Minh Đức',
    birthday: '11/03/2020',
    gender: 'Nam',
    group: 'Nhóm 3',
    status: 'Đánh giá',
    statusType: 'review',
    teacher: 'Cô Phạm Thu Hà',
    teacherNote: 'Giáo viên phụ trách',
    avatar: 'https://images.unsplash.com/photo-1509099836639-18ba1795216d?auto=format&fit=crop&w=420&q=80',
    teacherAvatar: 'https://i.pravatar.cc/80?img=5',
  },
  {
    id: 6,
    name: 'Đỗ Khánh Linh',
    birthday: '30/01/2019',
    gender: 'Nữ',
    group: 'Nhóm 3',
    status: 'Tạm dừng',
    statusType: 'paused',
    teacher: 'Cô Phạm Thu Hà',
    teacherNote: 'Giáo viên phụ trách',
    avatar: 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?auto=format&fit=crop&w=420&q=80',
    teacherAvatar: 'https://i.pravatar.cc/80?img=5',
  },
];
