export const menuItems = [
  { label: 'Tổng quan', icon: 'bi-house-door-fill' },
  { label: 'Thông tin trẻ', icon: 'bi-person-bounding-box' },
  { label: 'Chương trình can thiệp', icon: 'bi-journal-check' },
  { label: 'Kế hoạch can thiệp', icon: 'bi-calendar2-check', active: true },
  { label: 'Báo cáo can thiệp', icon: 'bi-clipboard2-data' },
  { label: 'Nhật ký can thiệp', icon: 'bi-journal-text' },
  { label: 'Lịch hẹn', icon: 'bi-calendar2-week' },
  { label: 'Tin nhắn', icon: 'bi-envelope' },
  { label: 'Cài đặt', icon: 'bi-gear' },
];

export const planTasks = [
  {
    id: 1,
    target: 'Trẻ gọi tên được người thân khi được hỏi.',
    field: 'Giao tiếp',
    fieldIcon: 'bi-chat-dots-fill',
    fieldClass: 'blue',
    support: 'Giảm hỗ trợ',
    supportClass: 'down',
    content: 'Gợi mở bằng câu hỏi và hình ảnh, sau đó giảm dần gợi ý để trẻ tự trả lời.',
  },
  {
    id: 2,
    target: 'Trẻ phân loại được đồ vật theo màu sắc (đỏ, vàng, xanh).',
    field: 'Nhận thức',
    fieldIcon: 'bi-lightbulb-fill',
    fieldClass: 'green',
    support: 'Không đổi',
    supportClass: 'same',
    content: 'Sử dụng thẻ màu và đồ vật thực tế. Luyện tập qua trò chơi phân loại.',
  },
  {
    id: 3,
    target: 'Trẻ xếp chồng 6 khối vuông thành tháp.',
    field: 'Vận động tinh',
    fieldIcon: 'bi-hand-index-thumb-fill',
    fieldClass: 'yellow',
    support: 'Giảm hỗ trợ',
    supportClass: 'down',
    content: 'Hướng dẫn mẫu, sau đó để trẻ tự thực hiện. Khích lệ và củng cố khi trẻ thành công.',
  },
  {
    id: 4,
    target: 'Trẻ chờ đến lượt khi chơi cùng bạn trong 3 lượt.',
    field: 'Kỹ năng xã hội',
    fieldIcon: 'bi-people-fill',
    fieldClass: 'pink',
    support: 'Tăng hỗ trợ',
    supportClass: 'up',
    content: 'Dùng đồng hồ đếm ngược, nhắc lượt bằng thẻ. Khen ngợi khi trẻ chờ đúng lượt.',
  },
  {
    id: 5,
    target: 'Trẻ tự rửa tay bằng xà phòng đúng 6 bước.',
    field: 'Tự chăm sóc',
    fieldIcon: 'bi-gift-fill',
    fieldClass: 'purple',
    support: 'Không đổi',
    supportClass: 'same',
    content: 'Hướng dẫn 6 bước qua tranh. Thực hành và kiểm tra lại từng bước.',
  },
];
