export const cartDemoItems = [
  {
    id: 1,
    field: 'Ngôn ngữ hiểu',
    target: 'Trẻ hiểu và thực hiện 2 bước chỉ dẫn liên tiếp',
    example: 'VD: “Lấy sách và đưa cho cô”',
    strategy: 'Chia nhỏ yêu cầu – Hỗ trợ từng phần',
    support: 'Hỗ trợ một phần',
    tone: 'blue',
    icon: '💡',
    child: '👧🏻',
    strategyIcon: 'bi-puzzle-fill',
  },
  {
    id: 2,
    field: 'Ngôn ngữ diễn đạt',
    target: 'Trẻ nói được câu 3 - 4 từ để diễn đạt nhu cầu',
    example: 'VD: “Con muốn uống nước”',
    strategy: 'Mô hình hóa – Mở rộng câu – Khuyến khích diễn đạt',
    support: 'Hỗ trợ ít',
    tone: 'green',
    icon: '💬',
    child: '👧🏻👦🏻',
    strategyIcon: 'bi-chat-square-dots-fill',
  },
  {
    id: 3,
    field: 'Nhận thức',
    target: 'Trẻ phân loại được đồ vật theo nhóm',
    example: 'VD: phân loại theo màu sắc',
    strategy: 'Dạy mẫu – Thực hành – Củng cố qua trò chơi',
    support: 'Hỗ trợ nhiều',
    tone: 'yellow',
    icon: '🧩',
    child: '👦🏻',
    strategyIcon: 'bi-puzzle-fill',
  },
  {
    id: 4,
    field: 'Vận động tinh',
    target: 'Trẻ sử dụng kéo cắt theo đường thẳng',
    example: 'VD: cắt giấy theo đường kẻ thẳng',
    strategy: 'Hướng dẫn tay – Thực hành từng bước',
    support: 'Hỗ trợ nhiều',
    tone: 'purple',
    icon: '✂️',
    child: '👦🏻',
    strategyIcon: 'bi-scissors',
  },
  {
    id: 5,
    field: 'Vận động thô',
    target: 'Trẻ nhảy lò cò 3 bước liên tiếp trên 1 chân',
    example: 'VD: nhảy lò cò theo đường thẳng',
    strategy: 'Dẫn dắt – Làm mẫu – Tăng dần khoảng cách',
    support: 'Hỗ trợ ít',
    tone: 'cyan',
    icon: '🏃',
    child: '👦🏻',
    strategyIcon: 'bi-cone-striped',
  },
  {
    id: 6,
    field: 'Cá nhân xã hội',
    target: 'Trẻ chào hỏi và tạm biệt người quen khi gặp',
    example: 'VD: “Con chào cô ạ”',
    strategy: 'Mô hình hóa – Nhắc nhở – Khen thưởng',
    support: 'Hỗ trợ một phần',
    tone: 'pink',
    icon: '🤝',
    child: '👧🏻👦🏻',
    strategyIcon: 'bi-heart-fill',
  },
  {
    id: 7,
    field: 'Hành vi',
    target: 'Trẻ giảm tần suất hành vi la hét khi không được như ý',
    example: '',
    strategy: 'Dạy kỹ năng thay thế – Tăng cường hành vi tích cực',
    support: 'Hỗ trợ nhiều',
    tone: 'orange',
    icon: '🛡️',
    child: '😣',
    strategyIcon: 'bi-shield-fill-check',
  },
  {
    id: 8,
    field: 'Tập trung chú ý',
    target: 'Trẻ ngồi làm việc tại bàn trong 5 phút liên tục',
    example: '',
    strategy: 'Thiết lập môi trường – Đồng hồ đếm ngược – Khen thưởng',
    support: 'Hỗ trợ ít',
    tone: 'sky',
    icon: '⏱️',
    child: '👧🏻',
    strategyIcon: 'bi-bullseye',
  },
];
