export const dataChildren = [
  {
    fullName: "Nguyễn Hoàng Bách",
    gender: "Nam",
    birth: "11/10/2021",
    teacherIds: ["vzPZKsn6QEeP0uKTh8bgisRhlwx2"],
  },
  {
    fullName: "Nguyễn Đức Hiếu",
    gender: "Nam",
    birth: "30/05/2024",
    teacherIds: ["vzPZKsn6QEeP0uKTh8bgisRhlwx2"],
  },
  {
    fullName: "Lữ Trọng Đức Thiện",
    gender: "Nam",
    birth: "20/08/2022",
    teacherIds: ["vzPZKsn6QEeP0uKTh8bgisRhlwx2"],
  },
  {
    fullName: "Trịnh Duy Anh",
    gender: "Nam",
    birth: "26/10/2021",
    teacherIds: ["Kh2ptgrGyLZDAd95l9IJDMxs7Xn2", "vzPZKsn6QEeP0uKTh8bgisRhlwx2"],
  },
  {
    fullName: "Nguyễn Thành Duy Long",
    gender: "Nam",
    birth: "04/06/2024",
    teacherIds: ["Kh2ptgrGyLZDAd95l9IJDMxs7Xn2","vzPZKsn6QEeP0uKTh8bgisRhlwx2"],
  },
  {
    fullName: "Trịnh Trọng Quang Huy",
    gender: "Nam",
    birth: "09/06/2023",
    teacherIds: ["Kh2ptgrGyLZDAd95l9IJDMxs7Xn2","vzPZKsn6QEeP0uKTh8bgisRhlwx2"],
  },
  {
    fullName: "Nguyễn Khánh Linh",
    gender: "Nữ",
    birth: "03/01/2023",
    teacherIds: ["Kh2ptgrGyLZDAd95l9IJDMxs7Xn2","vzPZKsn6QEeP0uKTh8bgisRhlwx2"],
  },
  {
    fullName: "Hoàng Đình Thành",
    gender: "Nam",
    birth: "23/06/2023",
    teacherIds: ["Kh2ptgrGyLZDAd95l9IJDMxs7Xn2","vzPZKsn6QEeP0uKTh8bgisRhlwx2"],
  },
  {
    fullName: "Phạm Gia Huy",
    gender: "Nam",
    birth: "15/04/2023",
    teacherIds: ["Cr9e9YJ1Ixfak7wigC6XphOFelG3","vzPZKsn6QEeP0uKTh8bgisRhlwx2"],
  },
  {
    fullName: "Nguyễn Văn Huy",
    gender: "Nam",
    birth: "10/01/2024",
    teacherIds: ["Cr9e9YJ1Ixfak7wigC6XphOFelG3","vzPZKsn6QEeP0uKTh8bgisRhlwx2"],
  },
  {
    fullName: "Nguyễn Quang Phúc",
    gender: "Nam",
    birth: "17/06/2024",
    teacherIds: ["Cr9e9YJ1Ixfak7wigC6XphOFelG3","vzPZKsn6QEeP0uKTh8bgisRhlwx2"],
  },
  {
    fullName: "Nguyễn Tiến Đạt",
    gender: "Nam",
    birth: "02/07/2024",
    teacherIds: ["Cr9e9YJ1Ixfak7wigC6XphOFelG3","vzPZKsn6QEeP0uKTh8bgisRhlwx2"],
  },
  {
    fullName: "Nguyễn Trung Hiếu",
    gender: "Nam",
    birth: "10/09/2016",
    teacherIds: ["oCipOTvUsKWDdRymauKT9aCrF5R2","vzPZKsn6QEeP0uKTh8bgisRhlwx2"],
  },
  {
    fullName: "Vũ Quỳnh Anh",
    gender: "Nam",
    birth: "29/07/2024",
    teacherIds: ["oCipOTvUsKWDdRymauKT9aCrF5R2","vzPZKsn6QEeP0uKTh8bgisRhlwx2"],
  },
  {
    fullName: "Trần Minh Quân",
    gender: "Nam",
    birth: "07/12/2021",
    teacherIds: ["nUn8idtsWoPrdTmiuZFcY5SGCN02","vzPZKsn6QEeP0uKTh8bgisRhlwx2"],
  },
  {
    fullName: "Đoàn Đức Việt",
    gender: "Nam",
    birth: "12/01/2023",
    teacherIds: ["nUn8idtsWoPrdTmiuZFcY5SGCN02","vzPZKsn6QEeP0uKTh8bgisRhlwx2"],
  },
  {
    fullName: "Phạm Trí Dũng",
    gender: "Nam",
    birth: "02/11/2019",
    teacherIds: ["nUn8idtsWoPrdTmiuZFcY5SGCN02","vzPZKsn6QEeP0uKTh8bgisRhlwx2"],
  },
  {
    fullName: "Nguyễn Lê Na",
    birth: "09/07/2023",
    teacherIds: ["rRx9iRapLzQbciK8RomzNaiDw6w2","vzPZKsn6QEeP0uKTh8bgisRhlwx2"],
  },
  {
    fullName: "Trịnh Minh Hoàng",
    gender: "Nam",
    birth: "09/08/2020",
    teacherIds: ["rRx9iRapLzQbciK8RomzNaiDw6w2","vzPZKsn6QEeP0uKTh8bgisRhlwx2"],
  },
  {
    fullName: "Trịnh Nguyễn Anh Khoa",
    gender: "Nam",
    birth: "30/10/2022",
    teacherIds: ["rRx9iRapLzQbciK8RomzNaiDw6w2","vzPZKsn6QEeP0uKTh8bgisRhlwx2"],
  },
  {
    fullName: "Lưu Nhật Anh",
    gender: "Nam",
    birth: "02/08/2023",
    teacherIds: ["N8s1nfkhxETijaMIliaL31TtVqk2","vzPZKsn6QEeP0uKTh8bgisRhlwx2"],
  },
  {
    fullName: "Bùi Thế Bảo",
    gender: "Nam",
    birth: "17/07/2024",
    teacherIds: ["N8s1nfkhxETijaMIliaL31TtVqk2","vzPZKsn6QEeP0uKTh8bgisRhlwx2"],
  },
  {
    fullName: "Lữ Minh Thanh",
    gender: "Nam",
    birth: "11/11/2021",
    teacherIds: ["N8s1nfkhxETijaMIliaL31TtVqk2","vzPZKsn6QEeP0uKTh8bgisRhlwx2"],
  },
  {
    fullName: "Nguyễn Sơn Tùng",
    gender: "Nam",
    birth: "23/03/2022",
    teacherIds: ["N8s1nfkhxETijaMIliaL31TtVqk2","vzPZKsn6QEeP0uKTh8bgisRhlwx2"],
  },
  {
    fullName: "Vũ Văn Dũng",
    gender: "Nam",
    birth: "13/10/2022",
    teacherIds: ["htcHg1idVFegvopOGEPSLW3n2N92","vzPZKsn6QEeP0uKTh8bgisRhlwx2"],
  },
  {
    fullName: "Bùi Đức Anh",
    gender: "Nam",
    birth: "27/09/2023",
    teacherIds: ["htcHg1idVFegvopOGEPSLW3n2N92","vzPZKsn6QEeP0uKTh8bgisRhlwx2"],
  },
  {
    fullName: "Nguyễn Minh Phong",
    gender: "Nam",
    birth: "26/08/2020",
    teacherIds: ["htcHg1idVFegvopOGEPSLW3n2N92","vzPZKsn6QEeP0uKTh8bgisRhlwx2"],
  },
  {
    fullName: "Mai Đăng Huy",
    gender: "Nam",
    birth: "13/08/2020",
    teacherIds: ["rRx9iRapLzQbciK8RomzNaiDw6w2","vzPZKsn6QEeP0uKTh8bgisRhlwx2"],
  },
];
