export const menuItems = [
  { label: 'Tổng quan', icon: 'bi-house-door' },
  { label: 'Thông tin trẻ', icon: 'bi-person-badge' },
  { label: 'Ngân hàng mục tiêu', icon: 'bi-bullseye' },
  { label: 'Kế hoạch can thiệp', icon: 'bi-calendar2-check' },
  { label: 'Báo cáo can thiệp', icon: 'bi-clipboard2-data' },
  { label: 'Chờ duyệt', icon: 'bi-clock' },
  { label: 'Giỏ mục tiêu', icon: 'bi-cart3', active: true },
];

export const cartTargets = [
  {
    id: 1,
    field: 'Ngôn\nngữ hiểu',
    fieldColor: 'blue',
    icon: '💡',
    child: '👧',
    target: 'Trẻ hiểu và thực hiện 2 bước chỉ dẫn liên tiếp',
    example: 'VD: “Lấy sách và đưa cho cô”',
    strategyIcon: 'bi-puzzle-fill',
    strategyColor: 'blue',
    strategy: 'Chia nhỏ yêu cầu –\nHỗ trợ từng phần',
    support: 'Hỗ trợ một phần',
    supportType: 'medium',
  },
  {
    id: 2,
    field: 'Ngôn ngữ\ndiễn đạt',
    fieldColor: 'green',
    icon: '💬',
    child: '👩‍🏫',
    target: 'Trẻ nói được câu 3 - 4 từ để diễn đạt nhu cầu',
    example: 'VD: “Con muốn uống nước”',
    strategyIcon: 'bi-chat-square-heart-fill',
    strategyColor: 'green',
    strategy: 'Mô hình hóa – Mở rộng câu –\nKhuyến khích diễn đạt',
    support: 'Hỗ trợ ít',
    supportType: 'low',
  },
  {
    id: 3,
    field: 'Nhận\nthức',
    fieldColor: 'yellow',
    icon: '🧩',
    child: '👦',
    target: 'Trẻ phân loại được đồ vật theo nhóm',
    example: 'VD: phân loại theo màu sắc',
    strategyIcon: 'bi-puzzle',
    strategyColor: 'yellow',
    strategy: 'Dạy mẫu – Thực hành –\nCủng cố qua trò chơi',
    support: 'Hỗ trợ nhiều',
    supportType: 'high',
  },
  {
    id: 4,
    field: 'Vận\nđộng tinh',
    fieldColor: 'purple',
    icon: '✂️',
    child: '👦',
    target: 'Trẻ sử dụng kéo cắt theo đường thẳng',
    example: 'VD: cắt giấy theo đường kẻ thẳng',
    strategyIcon: 'bi-scissors',
    strategyColor: 'purple',
    strategy: 'Hướng dẫn tay –\nThực hành từng bước',
    support: 'Hỗ trợ nhiều',
    supportType: 'high',
  },
  {
    id: 5,
    field: 'Vận\nđộng thô',
    fieldColor: 'blue',
    icon: '🏃',
    child: '👦',
    target: 'Trẻ nhảy lò cò 3 bước liên tiếp trên 1 chân',
    example: 'VD: nhảy lò cò theo đường thẳng',
    strategyIcon: 'bi-cone-striped',
    strategyColor: 'blue',
    strategy: 'Dẫn dắt – Làm mẫu –\nTăng dần khoảng cách',
    support: 'Hỗ trợ ít',
    supportType: 'low',
  },
];
